// <auto-generated />
namespace InventorySystem.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addmanagerialrole : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addmanagerialrole));
        
        string IMigrationMetadata.Id
        {
            get { return "202004121552414_add managerial role"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
