// <auto-generated />
namespace InventorySystem.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class changedstatustostringobject : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedstatustostringobject));
        
        string IMigrationMetadata.Id
        {
            get { return "202004121727539_changed status to string object"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
