// <auto-generated />
namespace InventorySystem.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class TestedDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TestedDb));
        
        string IMigrationMetadata.Id
        {
            get { return "202004112236343_TestedDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
